import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from "@/parts";
// import './globals.css'
import '@/style/main.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'header'}>
          더움바다의 개발 테스트 페이지
        </div>
        <div className={'main__contents--container'}>
          <Sidebar />
          <div className={'main__contents--block'}>
            {children}
          </div>
        </div>
        <div className={'footer'}>
          Created by Electornic
        </div>
      </body>
    </html>
  )
}
